export interface Account{
      customerId : number;
      title : string;
      firstName: string ;
      lastName : string;
      middleName: string ;
     mobileno : number ;
      emailId : string;
     aadhaarCardNumber : number ;
      dob : string;
      residentialAddressLine1: string ;
      residentialAddressLine2: string ;
      residentialLandmark: string ;
      residentialState: string ;
      residentialCity : string;
      residentialPincode  : number;
      rermanentAddressLine1: string ;
      permanentAddressLine2 : string;
      permanentLandmark : string;
      permanentState: string ;
      permanentCity : string;
      permanentPincode : number;
      occupationdetails : string;
      occupationType: string ;
      sourceofincome : string;
      grossAnnualIncome : number;
      status : string;
      accountBalance : number;
      credentialId : number ;
}